[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
ast = true

evm_version = "shanghai" # simulation may be false positive on bsc (PUSH0 opcode support)

optimizer=true
optimizer_runs=1000000

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

fs_permissions = [
    { access = "read-write", path = "./"},
    { access = "none", path = ".env"} # TODO: check if it overrides previous rule
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
